[package]
name = "x86-bare-metal-3d"
version = "0.1.0"
authors = ["Robin Lange <robin.langenc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.8"
micromath = "2.0.0"
